PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE USER_ROLE(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USER_ID INTEGER,
        ROLE_ID INTEGER
);
INSERT INTO "USER_ROLE" VALUES(1,3,1);
INSERT INTO "USER_ROLE" VALUES(5,1,2);
CREATE TABLE PERMISSION(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PERMISSION VARCHAR NOT NULL,
        ACCESS_LEVEL INTEGER NOT NULL
);
INSERT INTO "PERMISSION" VALUES(1,'QUERY',1);
INSERT INTO "PERMISSION" VALUES(2,'ADD',2);
INSERT INTO "PERMISSION" VALUES(3,'UPDATE',2);
INSERT INTO "PERMISSION" VALUES(4,'DELETE',3);
CREATE TABLE "ROLE" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"NAME" VARCHAR NOT NULL , "ACCESS_LEVEL" INTEGER NOT NULL  DEFAULT 1);
INSERT INTO "ROLE" VALUES(1,'USER',1);
INSERT INTO "ROLE" VALUES(2,'MANAGER',2);
INSERT INTO "ROLE" VALUES(3,'ADMIN',3);
CREATE TABLE "USER" ("ID" INTEGER PRIMARY KEY ,"USERNAME" VARCHAR(255) NOT NULL ,"PASSWORD" VARCHAR NOT NULL ,"ACCESS" BOOLEAN NOT NULL  DEFAULT (1) ,"CREATE_DATE" DATE NOT NULL ,"MODIFIED_DATE" DATE NOT NULL );
INSERT INTO "USER" VALUES(1,'qy','11c605501e726325aa170897acebe463',1,1470987173530,1470987173530);
INSERT INTO "USER" VALUES(2,'sjw','47bce5c74f589f4867dbd57e9ca9f808',1,1470993066643,1470993066643);
INSERT INTO "USER" VALUES(3,'a','47bce5c74f589f4867dbd57e9ca9f808',1,1471334809662,1471334809662);
CREATE TABLE "USER_PRODUCT" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT , "USER_ID" INTEGER NOT NULL , "PRODUCT_ID" INTEGER NOT NULL , "BUY_DATE" DATETIME NOT NULL , "AMOUNTS" INTEGER NOT NULL  DEFAULT 1);
CREATE TABLE "MENU" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "NAME" VARCHAR NOT NULL );
INSERT INTO "MENU" VALUES(1,'Novel');
INSERT INTO "MENU" VALUES(2,'Reference Book');
INSERT INTO "MENU" VALUES(3,'Dictionary');
CREATE TABLE "MENU_SUB" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "NAME" VARCHAR NOT NULL , "REL_MENU" INTEGER NOT NULL );
INSERT INTO "MENU_SUB" VALUES(1,'Detactive',1);
INSERT INTO "MENU_SUB" VALUES(2,'Science',1);
INSERT INTO "MENU_SUB" VALUES(3,'School',1);
INSERT INTO "MENU_SUB" VALUES(4,'documentary',1);
INSERT INTO "MENU_SUB" VALUES(5,'Primary',2);
INSERT INTO "MENU_SUB" VALUES(6,'Junior',2);
INSERT INTO "MENU_SUB" VALUES(7,'Senior',2);
INSERT INTO "MENU_SUB" VALUES(8,'University',2);
CREATE TABLE "BROWSE_RECORD" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"PRODUCTID" INTEGER NOT NULL  DEFAULT (null) ,"USERNAME" VARCHAR NOT NULL ,"BROWSEDATE" TIMESTAMP NOT NULL ,"BROWSETIMES" INTEGER NOT NULL  DEFAULT (1) );
INSERT INTO "BROWSE_RECORD" VALUES(1,1,'a',1485411186116,15);
INSERT INTO "BROWSE_RECORD" VALUES(2,4,'a',1485150415923,1);
INSERT INTO "BROWSE_RECORD" VALUES(3,3,'a',1485158879496,4);
INSERT INTO "BROWSE_RECORD" VALUES(4,2,'a',1485401203294,12);
CREATE TABLE "PRODUCT" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"NAME" VARCHAR NOT NULL ,"PRICE" FLOAT NOT NULL  DEFAULT (0) ,"CATEGORY" VARCHAR,"TAGS" VARCHAR,"DESCRIPTION" VARCHAR,"REMAINS" DOUBLE NOT NULL ,"IMG" VARCHAR NOT NULL  DEFAULT ('/ShiroTest/img/example.png') ,"RECOMMENDED" BOOL DEFAULT (0) );
INSERT INTO "PRODUCT" VALUES(1,'Book1',25.0,'Novel','Science, Dectative,Acient','xxxxxxxxxxxxxxx',560.0,'/ShiroTest/img/example.png',1);
INSERT INTO "PRODUCT" VALUES(2,'Book2',18.0,'Children','Story,Education','xxxxxxxxxxxxxxx',200.0,'/ShiroTest/img/example.png',1);
INSERT INTO "PRODUCT" VALUES(3,'Book3',30.0,'Education','Primary School,Math','xxxxxxxxxxxxxxx',333.0,'/ShiroTest/img/example.png',1);
INSERT INTO "PRODUCT" VALUES(4,'Book4',22.0,'Novel','School','xxxxxxxx',228.0,'/ShiroTest/img/example.png',1);
CREATE TABLE "PRODUCT_COMMENTS" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"PRODUCTID" INTEGER NOT NULL  DEFAULT (null) ,"USERID" INTEGER NOT NULL  DEFAULT (null) ,"COMMENTS" VARCHAR NOT NULL , "PICS" VARCHAR);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('USER_ROLE',5);
INSERT INTO "sqlite_sequence" VALUES('PERMISSION',4);
INSERT INTO "sqlite_sequence" VALUES('MENU',3);
INSERT INTO "sqlite_sequence" VALUES('MENU_SUB',8);
COMMIT;
