CREATE TABLE "BROWSE_RECORD" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"PRODUCTID" INTEGER NOT NULL  DEFAULT (null) ,"USERNAME" VARCHAR NOT NULL ,"BROWSEDATE" TIMESTAMP NOT NULL ,"BROWSETIMES" INTEGER NOT NULL  DEFAULT (1) );
CREATE TABLE "IMPORT_RECORD" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"PRODUCT_ID" INTEGER NOT NULL  DEFAULT (-1), "PRODUCT_NAME" VARCHAR NOT NULL ,"ADMIN_ID" INTEGER NOT NULL  DEFAULT (-1) ,"ADMIN_NAME" VARCHAR NOT NULL ,"AMOUNT" INTEGER NOT NULL ,IMPORT_DATE DATETIME NOT NULL DEFAULT(DATETIME(CURRENT_TIMESTAMP,'localtime')));
CREATE TABLE "MENU" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "NAME" VARCHAR NOT NULL );
CREATE TABLE "MENU_SUB" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "NAME" VARCHAR NOT NULL , "REL_MENU" INTEGER NOT NULL );
CREATE TABLE PERMISSION(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PERMISSION VARCHAR NOT NULL,
        ACCESS_LEVEL INTEGER NOT NULL
);
CREATE TABLE "PRODUCT" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"NAME" VARCHAR NOT NULL ,"PRICE" FLOAT NOT NULL  DEFAULT (0) ,"CATEGORY" VARCHAR,"TAGS" VARCHAR,"DESCRIPTION" VARCHAR,"REMAINS" DOUBLE NOT NULL ,"IMG" VARCHAR NOT NULL  DEFAULT ('/ShiroTest/img/example.png') ,"RECOMMENDED" BOOL DEFAULT (0) ,"ACCOUNTPRICE" FLOAT DEFAULT (0) );
CREATE TABLE "PRODUCT_COMMENTS" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"PRODUCTID" INTEGER NOT NULL  DEFAULT (null) ,"USERID" INTEGER NOT NULL  DEFAULT (null) ,"COMMENTS" VARCHAR NOT NULL , "PICS" VARCHAR, "COMMENTDATE" DATETIME);
CREATE TABLE "ROLE" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"NAME" VARCHAR NOT NULL , "ACCESS_LEVEL" INTEGER NOT NULL  DEFAULT 1);
CREATE TABLE "USER" ("ID" INTEGER PRIMARY KEY ,"USERNAME" VARCHAR(255) NOT NULL ,"PASSWORD" VARCHAR NOT NULL ,"ACCESS" BOOLEAN NOT NULL  DEFAULT (1) ,"CREATE_DATE" DATE NOT NULL ,"MODIFIED_DATE" DATE NOT NULL );
CREATE TABLE "ORDER_LIST" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT , "USER_ID" INTEGER NOT NULL , "PRODUCT_ID" VARCHAR NOT NULL , "BUY_DATE" DATETIME NOT NULL , "SUM" INTEGER NOT NULL  DEFAULT 1);
CREATE TABLE USER_ROLE(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USER_ID INTEGER,
        ROLE_ID INTEGER
);
