mybatis:
  type-aliases-package: com.sjw.ShiroTest.Pojo
  mapper-locations: Mapper/*.xml

server:
  session:
    timeout: 1800

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    username: guest
    password: guest
